import './globals.css'
import { PropsWithChildren } from 'react'

import { Inter } from 'next/font/google'

import type { Metadata } from 'next'

import { RootProvider } from './_provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Turborepo',
  description: 'Generated by create turbo',
}

const RootLayout = ({ children }: PropsWithChildren) => (
  <html lang="en">
    <body className={inter.className}>
      <RootProvider>{children}</RootProvider>
    </body>
  </html>
)

export default RootLayout
